### ISSUE TITLE
initial release install error

### ISSUE THREAD

**Issue by DavidFW1960** [kanine/bomWeather-2020#1]
Error:

Invalid package:
bomWeather-2020-0.1.rmskin

The Skin Packager tool must be used to create valid .rmskin packages

This is generally build within rainmeter..

**Comment by kanine** [comment]
Suspect this is something missing in the zip file that githubs creating, I'll check it out.

**Comment by kanine** [comment]
> (As of version 2.3, Rainmeter will not install a normal ZIP file changed to the ".rmskin" extension; the package must be created with the Skin Packager.)

Looks like I'll have to make one as part of the distribution, otherwise change the install instructions which is frankly a little easier on maintenance.

**Comment by DavidFW1960** [comment]
Ah makes sense.
The ABB one I maintain I don't do releases at all I just upload the .rmskin file and people download that.

**Comment by kanine** [comment]
I've updated the installation instructions for now but will leave this open as a reminder. If I can script the generation I'll incorporate a distribution of a .rmskin in the future.

**Comment by kanine** [comment]
Unfortunately I've not been able to reproduce this. Closing for now.
