### ISSUE TITLE
Error when day 6 unavailable?

### ISSUE THREAD

**Issue by DavidFW1960** [kanine/bomWeather-2020#4]
I thought you fixed this but today:
![image](https://user-images.githubusercontent.com/36390762/104859159-52cbcb80-5977-11eb-896e-47e8826f45e7.png)
Error on refresh

**Comment by kanine** [comment]
I think this is unrelated, the observation API now seems to want to use the parent geohash, it still seems to get the same weather station for me. Give the latest push a go, create the debug.on file in the script folder and then check the data\observations.json for any messages.

**Comment by DavidFW1960** [comment]
Seems ok so far.... I'll let you know in a day or so..
