### ISSUE TITLE
Windows Script Host Error

### ISSUE THREAD

**Issue by haramdaddy** [kanine/bomWeather-2020#5]
![2021-10-30_19-10](https://user-images.githubusercontent.com/20486036/139525482-7535b485-f073-4c7a-8961-a4b1506e84df.png)

How do I fix this error?

**Comment by DavidFW1960** [comment]
Are you running the latest version?

**Comment by haramdaddy** [comment]
I believe I am. I installed this skin back in July 2021 btw. This error comes once a month and goes away after 2-3 days but I'd like to weed out the root cause of the error.

**Comment by haramdaddy** [comment]
Disregard that. I am running version 0.1a and the latest is 0.1e. Ill try that out.

**Comment by haramdaddy** [comment]
The latest version hasn't fixed  anything either.

**Comment by DavidFW1960** [comment]
Interesting as I seem to remember this was a fixed error in a later version. Better wait for Kanine to advise but I have been running this even before release and it's working perfectly for me.

**Comment by kanine** [comment]
@haramdaddy I'd need to have your config file to test this out, if it's intermittent then there's possibly something odd in the feed from the BoM now and then.

You will find the config file bomWeather-2020-Configuration.txt in %APPDATA%\Rainmeter-kanine

**Comment by haramdaddy** [comment]
[bomWeather-2020-Configuration.txt](https://github.com/kanine/bomWeather-2020/files/7450389/bomWeather-2020-Configuration.txt)

Here it is.

**Comment by kanine** [comment]
That's working fine for me, does it always fail or just intermittent. 

You also can try running Documents\Rainmeter\Skins\bomWeather-2020\@Resources\Scripts\bomWeather.vbs through a double click and see if you get some kind of Windows permission error.

**Comment by haramdaddy** [comment]
Now it seems to work. I'd say that the issue is intermittent. I could weeks without any issue and it would stop working suddenly. My strategy at this stage is to just unload the skin for 48 hours and see if it has fixed itself after. Thanks for your help btw.
